name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-go-installation: true
          args: --timeout 3m --verbose
