name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set git
      run: git config --global url."https://kooksee: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@github.com".insteadOf "https://github.com"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        args: --timeout 3m --verbose
