name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.0

      - name: Run
        shell: bash
        run: |
          go env -w GOPRIVATE=gitlab.com/pubgo/*
          git config --global url."https://kooksee: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@github.com".insteadOf "https://github.com"
          env
          go version
          go mod tidy
          go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          args: --timeout 3m --verbose
