name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.0

      - name: Run
        shell: bash
        run: |
          git config --global url."https://kooksee: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@github.com".insteadOf "https://github.com"
          go version
          export GOPRIVATE=github.com/pubgo
          export GOPRIVATE=github.com/pubgo
          export GONOPROXY="github.com/pubgo"
          export GONOSUMDB="github.com/pubgo"
          export GOPRIVATE="github.com/pubgo"
          go mod tidy
          go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          args: --timeout 3m --verbose
